//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_multass
    {
        public string legajo { get; set; }
        public Nullable<int> antiguedad { get; set; }
        public string APELLIDO_AGENTE { get; set; }
        public string NOMBRES_AGENTE { get; set; }
        public string LOCALIDAD { get; set; }
        public string patente { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO { get; set; }
        public string Descripcion { get; set; }
    }
}
